### ISSUE TITLE
Build OakCLI for Linux32, Linux64, OSX

### ISSUE THREAD

**Issue by digistump** [digistump/OakCLI#1]
Builds clean with nexe - if anyone has a chance to build on these platforms and upload it would be much appreciated.

Install node.js
Install python
"npm install -g nexe"
Download this repository, cd to it
"npm install"
"nexe -i ./oak.js -o ./oak"
Upload executable here

**Comment by CompyENG** [comment]
Here's a build for Linux64: 
[oakcli.zip](https://github.com/digistump/OakCLI/files/95234/oakcli.zip)

**Comment by digistump** [comment]
wow thanks @TrueJournals - I figured this was worth posting while I was working on the rest, wasn't sure anyone would actually build it!

**Comment by digistump** [comment]
@TrueJournals if you have a moment can you run this one for me too? digistump/OakCore#11 - thanks!

**Comment by DarkLotus** [comment]
Hah i was too slow, i just built linux64 against 1f4b889 and pushed to my fork.
I've also got OSX building as well incase no one else does.

**Comment by CompyENG** [comment]
@digistump Happy to help out :smile:  Just built digistump/OakCore#11 .  Looking forward to playing around with my Oak!

**Comment by digistump** [comment]
@DarkLotus - care to build this one on OSX too: digistump/OakCore/issues/11 - despite working on a macbook pro I'm working in windows ATM and would be most grateful to not have to close out for a reboot

**Comment by DarkLotus** [comment]
[oak.zip](https://github.com/digistump/OakCLI/files/95282/oak.zip)
Here's OSX. built with node 5.4.1 and OS X 10.10

**Comment by DarkLotus** [comment]
[oak-linux32.zip](https://github.com/digistump/OakCLI/files/95522/oak-linux32.zip)

32 bit linux build

**Comment by digistump** [comment]
@DarkLotus @TrueJournals - any chance you two could rebuild from latest commit, ran into an issue with the sparkjs library and how it handles paths

beta release coming tonight!

**Comment by DarkLotus** [comment]
will do now.

**Comment by DarkLotus** [comment]
[oakcli32.zip](https://github.com/digistump/OakCLI/files/100421/oakcli32.zip)
32 bit linux

[oakosx.zip](https://github.com/digistump/OakCLI/files/100426/oakosx.zip)
osx 10.10

64bit linux coming

**Comment by DarkLotus** [comment]
[oak64.zip](https://github.com/digistump/OakCLI/files/100446/oak64.zip)
64bit linux all compiled against edadb53

**Comment by digistump** [comment]
@DarkLotus any chance you can build this for linux and osx, if you get a moment before I do: https://github.com/digistump/OakCLI/releases/tag/1.0.0

Must run "npm install" even if overwriting existing install as one module is updated and one added

Thanks!

**Comment by jhitze** [comment]
I'm building the OSX version right now. This takes much longer than I expected.

**Comment by jhitze** [comment]
Apparently my xcode is out of date, so I'm updating now. Grr.

**Comment by jhitze** [comment]
Here's the OSX version.
[oak-osx.zip](https://github.com/digistump/OakCLI/files/120139/oak-osx.zip)

A note: 
- I had to have >XCode7.2 installed to compile with `nexe`. I don't normally work with Node.js, so this was an interesting find.

**Comment by jhitze** [comment]
Built on Ubuntu Trusty x64
[oak-linux-x64.zip](https://github.com/digistump/OakCLI/files/120143/oak-linux-x64.zip)

``` bash
~/OakCLI$ file oak
oak: ELF 64-bit LSB  executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=6fc85db30d414c187a0ad10240f97f2eae4f02b8, not stripped
```

**Comment by jhitze** [comment]
Built (finally) on Ubuntu Trusty x86
[oak-linux-x86.zip](https://github.com/digistump/OakCLI/files/120167/oak-linux-x86.zip)

``` shell
file oak
oak: ELF 32-bit LSB  executable, Intel 80386, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=968063cc84cc3f0d5e2f30808dbd00546f5a6298, not stripped
```

**Comment by digistump** [comment]
@jhitze - any chance you could upload the linux x64 version again - github seems to have lost the file!

Thank you so much for compiling these!

**Comment by jhitze** [comment]
Aye-aye boss-man. 

x64 Version, take 2!

[oak-linux-x64.zip](https://github.com/digistump/OakCLI/files/128755/oak-linux-x64.zip)

Do you want me to submit a pull request for the scripts I used? I built a vagrant file to actually build the VMs and provision them.

**Comment by digistump** [comment]
Thank you very much!

A pull request with the scripts would be super awesome, I've been wanting
to do something just like that.

Thanks again!

**Comment by digistump** [comment]
@jhitze or @DarkLotus Any chance one of you could run the latest builds for OSX, linux32, and linux64 - haven't quite got the build scripts from @jhitze dialed in on my end yet and would love to be able to push this full package tomorrow

@jhitze - thanks for the build scripts! I've used them as the jumping off point for fully automated builds with some changes (changed to 12.04, tar instead of zip, file naming with version, etc) and adding a vagrant setup for the osx and windows builds as well.

**Comment by thunderace** [comment]
I think there is a problem with these scripts. nodejs 12.04 is installed but nexe use by default the latest nodejs version (5.7.0) not good for us i think.
We have to set the nodejs version during nexe build (-r option).

**Comment by digistump** [comment]
Thanks for pointing that out - I've switched to using 0.12.10 for the nexe builds

Also got all the build scripts and boxes working, so I no longer need anyone to build these - thanks!
