### ISSUE TITLE
Confusing DOCS: Connecting and Programming Your Oak

### ISSUE THREAD

**Issue by Defragster** [digistump/OakCLI#14]
Reading this: http://digistump.com/wiki/oak/tutorials/arduino
- It led me here to get a GITHUB ZIP?  
  ◾ You now must set up your Particle Cloud login so you can upload to your device. Download the OakCLI tool from here: https://github.com/digistump/OakCLI 
- Reading the READ.MD I found this is what I needed as there was No tool for this in this github?

**Download:** 
- [Windows](https://github.com/digistump/OakCLI/releases/download/1.0.0/oakcli-1.0.0-win32.zip)
- [Mac OSX](https://github.com/digistump/OakCLI/releases/download/1.0.0/oakcli-1.0.0-osx.tar.gz)
- [Linux 32bit](https://github.com/digistump/OakCLI/releases/download/1.0.0/oakcli-1.0.0-linux32.tar.gz)
- [Linux 64bit](https://github.com/digistump/OakCLI/releases/download/1.0.0/oakcli-1.0.0-linux64.tar.gz)

**Comment by digistump** [comment]
added direct links to wiki - thanks

**Comment by Defragster** [comment]
Cool
