### ISSUE TITLE
Triple Blink achieved - but no Particle registered units?

### ISSUE THREAD

**Issue by Defragster** [digistump/OakCLI#15]
I got final 6 OAKS today.
- On my Phone I followed and logged onto Particle : http://rawgit.com/digistump/OakSoftAP/master/config.html
- Went offline to the ACORN_XXX WiFi
- Of the 6 two ended up doing the TRIPLE BLINK ready to take an IDE upload.  
- The other four went through what appeared to be the update process - various faster blinks and such, but no Triple Blink
- In the end after hours away the only OAK I have showing or Particle dashboard is my initial BATE OAK from 2/25?

I assume I did the right URL to rawgit - it was stored in my phone, did a timeout countdown to allow the update to complete?
- I did cheat and waited for the timeout
- I then powered the next OAK, connect to its new ACORN_XXX WiFi
- I then went back and did 'Retry' and it proceeded just fine without having to log in again
- It was on the middle of these 6 units that two went to 'Triple Blink'
- Still no new units on Particle - so I cannot select one to upload from the IDE?

I've got a few minutes again - I'll go through the six and see if they are powering up as ACORN_XXX or joining the network?

**Comment by digistump** [comment]
Hey @defragster - confusing where to post I know, but per the last update
please post support requests only to the forum in the future:
digistump.com/board - issues are for confirmed bugs in the code.

Several people with similar issues on the forum - here's one that seems
similar: http://digistump.com/board/index.php/topic,2103.0/topicseen.html -
and some ideas for diagnosing and fixing are listed.

Questions for you: During the config did you get to success where it said
your Oak was ready to go and on the cloud? Or did you get an error? Did you
force a refresh of the config.html?

Thanks,
Erik

**Comment by Defragster** [comment]
Seeing the triple blink and no registration seemed like a real bug - I did my part - and saw all signs of success.  The other four processed as well - but I titled the bug on the triple blinks I had every reason to believe should be moved to a registered and functional state - maybe a doc bug that misled me that triple blink meant the OAK.exe should see my unit to proceed with an upload?

As noted I ended up back within the RAWGIT/../config.html in all cases and then went to my next one since I had 6 to do.  They all proceeded through initial update blinks, but I never got any feedback on my phone - once I saw the device update I didn't expect to as it should have been registered and ready to run - especially the two that went to triple blink.

I'll go catch that forum link and see if it relates. That other ISSUE filed and closed made me come to github where doing this bug/issue was the obvious answer. Going back to my laptop where I can see what devices are on WiFi as I power the 6 OAKS ... will proceed from there . . . 

< edit >: BTW - I updated the 'OAK' machine to IDE 1.6.8, and installed OAK via JSON, and I could indeed still program my generic_ESP.

**Comment by digistump** [comment]
Closing as I see you've posted on the forum - thanks!

**Comment by Defragster** [comment]
Posted - but weirder and wierder

**Comment by Defragster** [comment]
4 of 6 went pretty easy on LOCAL SERVER :: http://digistump.com/wiki/oak/tutorials/local_update#local_update_tool

2 re-retried and no go - I reset server and started over - all SIX REGISTERED - thanks to LOCAL SERVER!

http://digistump.com/board/index.php/topic,2103.msg9700.html#msg9700
