### ISSUE TITLE
nexe.js:42967

### ISSUE THREAD

**Issue by joeycortez42** [digistump/OakCLI#20]
Using OakCLI 1.0.0 on Max OS X 10.11.4

Logging in to Particle...
nexe.js:42967
      if (config.devices[activeDeviceIndex].device_name !== undefined && activ
                        ^
TypeError: Cannot read property '-1' of undefined
    at nexe.js:42967:25
    at Spark.emitAndCallback (nexe.js:31179:42)
    at null.<anonymous> (nexe.js:31307:10)
    at Request.self.callback (nexe.js:28662:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (nexe.js:29499:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (nexe.js:29426:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

I thought maybe there was an old /home/user/.oak/config.json but I couldn't find anything. I then rebuilt the file from source and had the same error.

**Comment by ntorring** [comment]
I'm getting the same error. I've only just gotten around to playing with my Oak, so I don't know if this has work in the past, or if there is something wrong with my particle account.
Might it have something to do with **sparkjs** being deprecated in favor of **particle-api-js**?

**Comment by thunderace** [comment]
It's fixed even if i can't reproduce your problem. And i cannot build and test on OSX platform.
See Pull request #21

**Comment by joeycortez42** [comment]
Yup, this does fix the error issue. Thanks @thunderace!
