### ISSUE TITLE
Problem running oak CLI on Linux Mint 17.2 32-bit

### ISSUE THREAD

**Issue by lazerdye** [digistump/OakCLI#3]
I get this error when I run ./0.9.1/oak on my system:

./0.9.1/oak: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./0.9.1/oak)

It looks like it's compiled for a different version of glibc than I have.

$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"

$ dpkg -l | grep libstdc
ii  libstdc++6:i386                             4.8.4-2ubuntu1~14.04.1                              i386         GNU Standard C++ Library v3

**Comment by thunderace** [comment]
I think it's because nexe use the latest nodejs version during packaging.
Use the command line : node oak.js

**Comment by digistump** [comment]
I'm building new versions against Ubuntu 12.04 instead of 14.04 latest - that might help, otherwise you'll need to compile for your own platform or use node directly.

If anyone has any suggestions here (besides building for every major distro) to increase compatibility it would be most welcome!
