### ISSUE TITLE
Issue with OakCLI bin on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by ancientmidi** [digistump/OakCLI#4]
After upgrading to 0.9.3, kept getting Config file not found at: /home/(my home dir)/.oak/config.json. Confirmed the file was writing successfully, logging in fine.

Finally tracked down that the IDE on my system was calling it at:
~/.arduino15/packages/digistump/tools/oakcli/0.9.3

Even tried the latest oak-linux-64 binary from https://github.com/digistump/OakCLI/issues/1
(https://github.com/digistump/OakCLI/files/128755/oak-linux-x64.zip) same issue.

Replaced ~/.arduino15/packages/digistump/tools/oakcli/0.9.3/oak binary with old copy, message doesn't show issue, confirmed upload works after replacing bin.

**Comment by eurycea** [comment]
I am having the same issue on El Capitan
It is some issue around the dynamic require of the config file. 

> No such native module /Users/johndoe/Library/Preferences/oak/config.json

I can submit a pull request to to use a simple file read and parse.

**Comment by digistump** [comment]
Fixed in coming release - thank you both!
